// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.EntityFramework.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240623131950_AddingRegionModel")]
    partial class AddingRegionModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegiaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef8db920-21cc-4b59-a819-a7fe94469c1c"),
                            Nome = "Rio Branco",
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("8256a0ee-90ad-45e2-b198-fc1261130743"),
                            Nome = "Maceió",
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("a2c4f3fc-a094-4f1c-94a2-bd61661142cb"),
                            Nome = "Macapá",
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("f0402ad9-9f47-43c0-8ed8-bf1fd6a9c601"),
                            Nome = "Manaus",
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("e9990b57-1105-48d1-bc1a-0962c50feb7c"),
                            Nome = "Salvador",
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("dd90febd-aab5-4a75-afc6-619f51783076"),
                            Nome = "Fortaleza",
                            UF = "CE"
                        },
                        new
                        {
                            Id = new Guid("dc89eee0-8230-40c5-95f6-09948478aaa7"),
                            Nome = "Brasília",
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("fb0681dd-d004-4f74-9820-18f10095b949"),
                            Nome = "Vitória",
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("6bb67ad8-5527-4d0f-8e28-9f8e20f14b40"),
                            Nome = "Goiânia",
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("05f418ea-e145-43ec-80f4-91364843ed06"),
                            Nome = "São Luís",
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("cf754d1f-ed3f-4126-852b-4b8735fe967b"),
                            Nome = "Cuiabá",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("98b48aec-8408-4a98-8397-10ee0e80af09"),
                            Nome = "Campo Grande",
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("c99866de-e631-4671-bd84-60feef0a4400"),
                            Nome = "Belo Horizonte",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("399d4017-1b2c-4eae-aac0-3b8e1dbbc28f"),
                            Nome = "Belém",
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("bc2e2707-b6ed-48bd-9bf3-fd946369738d"),
                            Nome = "João Pessoa",
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("7a055054-2b7b-40ba-919f-187a94c7f529"),
                            Nome = "Curitiba",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("fff475d3-3784-49e5-83e3-9a51201d29a4"),
                            Nome = "Recife",
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("0322f421-cabf-43d2-bfa8-940aefe81335"),
                            Nome = "Teresina",
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("ef71bfcc-f094-4b49-8d35-37c402d7656f"),
                            Nome = "Rio de Janeiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("2b75bc34-d22a-4a23-b870-7969eece2a38"),
                            Nome = "Natal",
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("73a4bd88-79fb-40a7-a585-878337be7978"),
                            Nome = "Porto Alegre",
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("23b79468-ab86-4754-9e75-e306cb53a1a4"),
                            Nome = "Porto Velho",
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("fccb11ce-a4f5-4aa7-8eda-d6d1ec5b577a"),
                            Nome = "Boa Vista",
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("a7dbcc3d-0a51-43b0-95df-6b1c42a912c8"),
                            Nome = "Florianópolis",
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("6f13a8e6-96d0-4131-a765-2bad3ba63ee6"),
                            Nome = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("21944bfc-1b1d-4638-b33f-4d59f77911c4"),
                            Nome = "Aracaju",
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("009bf40f-5151-49a6-8d3e-2ed1fdf9eff9"),
                            Nome = "Palmas",
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regiao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sul"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sudeste"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Centro-Oeste"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Nordeste"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Norte"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegiaoCidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db8fbe01-1d7a-4518-8074-054569f05c83"),
                            IdRegiao = 5,
                            NomeCidade = "Rio Branco"
                        },
                        new
                        {
                            Id = new Guid("26556445-19a8-4c01-b3d8-d076a2cfe1f8"),
                            IdRegiao = 5,
                            NomeCidade = "Manaus"
                        },
                        new
                        {
                            Id = new Guid("e22cdc73-0848-405b-a506-5315ee945f09"),
                            IdRegiao = 5,
                            NomeCidade = "Goiânia"
                        },
                        new
                        {
                            Id = new Guid("2a6ffe39-d193-490e-b37d-bbb385ddffb2"),
                            IdRegiao = 5,
                            NomeCidade = "Belém"
                        },
                        new
                        {
                            Id = new Guid("056b175d-2d58-460f-a76a-97b561e68905"),
                            IdRegiao = 5,
                            NomeCidade = "Palmas"
                        },
                        new
                        {
                            Id = new Guid("445ff104-5e37-42b2-b7c5-f3f658407cb0"),
                            IdRegiao = 5,
                            NomeCidade = "Porto Velho"
                        },
                        new
                        {
                            Id = new Guid("478add8a-bb5a-4d8a-bd89-5ebf9a77ddbe"),
                            IdRegiao = 4,
                            NomeCidade = "Maceió"
                        },
                        new
                        {
                            Id = new Guid("3fc5e32e-0c9d-4894-88ef-398846115aab"),
                            IdRegiao = 4,
                            NomeCidade = "Macapá"
                        },
                        new
                        {
                            Id = new Guid("503733fc-18ac-4473-b2c9-ba105bd5eee6"),
                            IdRegiao = 4,
                            NomeCidade = "Salvador"
                        },
                        new
                        {
                            Id = new Guid("f628731a-cfea-4571-8f50-fb8b71ae960b"),
                            IdRegiao = 4,
                            NomeCidade = "Fortaleza"
                        },
                        new
                        {
                            Id = new Guid("40b11505-a5cf-49f7-8fe4-e24a9dad12f7"),
                            IdRegiao = 4,
                            NomeCidade = "São Luís"
                        },
                        new
                        {
                            Id = new Guid("a0e2345e-9b10-41be-91d7-9a135da18ee6"),
                            IdRegiao = 4,
                            NomeCidade = "Cuiabá"
                        },
                        new
                        {
                            Id = new Guid("22011e31-fa0f-4115-a8ec-437b0e00d648"),
                            IdRegiao = 4,
                            NomeCidade = "João Pessoa"
                        },
                        new
                        {
                            Id = new Guid("46c4c238-3738-42e2-8e64-7da4da5e73eb"),
                            IdRegiao = 4,
                            NomeCidade = "Recife"
                        },
                        new
                        {
                            Id = new Guid("ef8fa12a-01e3-4dfe-98e7-b800d0177349"),
                            IdRegiao = 4,
                            NomeCidade = "Teresina"
                        },
                        new
                        {
                            Id = new Guid("724e7e04-693a-488c-8816-33f62693db15"),
                            IdRegiao = 4,
                            NomeCidade = "Aracaju"
                        },
                        new
                        {
                            Id = new Guid("db2c9370-6240-4f14-bc21-b8cecfeadc40"),
                            IdRegiao = 4,
                            NomeCidade = "Boa Vista"
                        },
                        new
                        {
                            Id = new Guid("dc0e2d7c-0793-4d5b-902c-0d9eb273cb85"),
                            IdRegiao = 4,
                            NomeCidade = "Natal"
                        },
                        new
                        {
                            Id = new Guid("0b90bb63-7316-4b50-bb8c-7b317b0842a9"),
                            IdRegiao = 3,
                            NomeCidade = "Brasília"
                        },
                        new
                        {
                            Id = new Guid("40b6c2dd-4cc4-4659-9b3c-38a99574b2b2"),
                            IdRegiao = 3,
                            NomeCidade = "Cuiabá"
                        },
                        new
                        {
                            Id = new Guid("7df97669-af4b-4c47-8e50-b08fa0a5e9ab"),
                            IdRegiao = 3,
                            NomeCidade = "Campo Grande"
                        },
                        new
                        {
                            Id = new Guid("1e276809-4fe1-4e34-8bfe-8238ccae9f79"),
                            IdRegiao = 2,
                            NomeCidade = "Vitória"
                        },
                        new
                        {
                            Id = new Guid("0d4cefbc-902e-4bd9-a345-e9d5b22b8558"),
                            IdRegiao = 2,
                            NomeCidade = "Belo Horizonte"
                        },
                        new
                        {
                            Id = new Guid("40f6487d-3c24-4fa1-a4b2-8f60468401dd"),
                            IdRegiao = 2,
                            NomeCidade = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("eb8dc656-9ff9-41be-8176-5293f049497b"),
                            IdRegiao = 2,
                            NomeCidade = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("98b6ed3a-7e9c-4b0b-be07-7c1417ef4d20"),
                            IdRegiao = 1,
                            NomeCidade = "Curitiba"
                        },
                        new
                        {
                            Id = new Guid("e4cde0eb-d66d-4808-9fa1-1851e3376dee"),
                            IdRegiao = 1,
                            NomeCidade = "Florianópolis"
                        },
                        new
                        {
                            Id = new Guid("392b4666-9bf9-4c6c-a751-f6d6bbeb327d"),
                            IdRegiao = 1,
                            NomeCidade = "Porto Alegre"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", null)
                        .WithMany("Cidades")
                        .HasForeignKey("RegiaoId");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Cidades");
                });
#pragma warning restore 612, 618
        }
    }
}
